<!DOCTYPE html>
<HTML lang="Fr">

<head>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" type="text/css" href="css/style.css" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css"/>
   
    <meta charset="utf8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script
      src="https://code.jquery.com/jquery-3.4.1.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"></script>


      <title>
       Site fictif
    </title>
</head> 

<body>
    <p>Ceci est un site fictif crée dans le cadre d'une formation</p>
</body>

    <footer>
        <ul class="">
            <li><a href="Mentions legales" class ="text-black btn btn-outline-primary">Mentions légales</a></li>
            <li><a href="site fictif" class="text-black btn btn-outline-primary">Site fictif</a></li>
        </ul>
    </footer>
</body>
</HTML>

<?php
    
?>